remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Christine Tzeng -at- NCSU
github:
is\_project\_page: false

theme: jekyll-theme-hacker
